Changed required fields for Medtronic compatibility
someoneAnyone/Nightscouter pull request #70
Opened 2017-02-09 19:37 UTC by daveewall

I'm running a purely Medtronic setup, and the JSON objects returned from NS don't have some of the fields that Dexcom uses, so the code fails to retrieve the information properly.

I'm not the best Swift programmer, especially when it comes to question marks, so I'm sure there's a Swiftier way to handle this, but it does work for me as-is.

Also, can't test it with a Dexcom setup.

2017-02-09 20:48 UTC, rodericj commented on Common/Parsers/JSONParser.swift
> +        return SensorGlucoseValue(direction: direction!, device: device, rssi: rssi, unfiltered: unfiltered, filtered: filtered, mgdl: mgdl, noise: noise, milliseconds: mill)
It feels like explicitly unwrapping an option in the return here could be pretty risky. Looks like a lot of the necessary checks were done around line 386. I think we can be a little tighter about this. I don't know if/when I'd have a chance to take a look at it :(

2017-02-11 08:02 UTC, daveewall commented
Is this better?

2017-02-12 18:26 UTC, someoneAnyone requested changes
I'd rather see something like...
```swift
let directionString = json[JSONKey.direction] as? String ?? "None"
let filtered = json[JSONKey.filtered] as? Double ?? 0
let noiseInt = json[JSONKey.noise] as? Int ?? 0
let rssi = json[JSONKey.rssi] as? Int ?? 0
let unfiltered = json[JSONKey.unfiltered] as? Double ?? 0
        
let device = Device(rawValue: deviceString) ?? .unknown
              
let direction = Direction(rawValue: directionString) ?? .none
```

2017-02-12 18:30 UTC, daveewall commented
Forget it. I don't think it matters anyway.  After upgrading oref0 his morning, it seems they just added direction support for MDT sensors, which fixed the current version of the program, making this PR irrelevant anyway.

2017-02-12 18:30 UTC, closed without merging